# Prey species in the California drylands
## Week 1 - Discussion section

#### Description of the data
Link: https://knb.ecoinformatics.org/view/doi%3A10.5063%2FF1VM49RH

Date Accessed: Oct 1, 2026
- What is this data about?
- Is this data collected in situ by the authors or is it a synthesis of multiple datasets?
- During what time frame were the observations in the dataset collected?
- Does this dataset come with an associated metadata file?
- Does the dataset contain sensitive data?

In [1]:
import pandas as pd

# Read in the file from a URL
drylands = pd.read_csv('https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3A3baf7289-bf90-4db3-ad11-58785c09b26e')
drylands.describe()

       attribute                           description
count         40                                    40
unique        40                                    40
top        class  taxonomic class of observed organism
freq           1                                     1

In [2]:
prey = pd.read_csv('https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3A23d42528-1048-45d4-85d1-7e13b666e744')
print(type(prey))
prey.head(3)

<class 'pandas.core.frame.DataFrame'>

,class,order,family,genus,species,lat,long,eventDate,day,month,...,bio4,bio5,bio6,bio7,bio8,bio9,dist,dem90_hf,lc_class,ndvi
0,Insecta,Odonata,Libellulidae,Sympetrum,Sympetrum corruptum,37.173971,-121.856329,2020-09-29T08:24:00Z,29.0,9.0,...,4352.049805,289.341888,27.307756,262.034149,89.602631,196.067307,8.935099,352.799927,grassland,6343.969238
1,Malacostraca,Isopoda,Armadillidiidae,Armadillidium,Armadillidium vulgare,37.688580,-122.436608,2021-12-04T14:49:59Z,4.0,12.0,...,2455.836914,217.470047,61.847702,155.622360,107.227386,159.852875,2.005335,112.895271,grassland,4995.110352
2,Insecta,Hymenoptera,Apidae,Bombus,Bombus vosnesenskii,33.774911,-116.679713,2021-06-18T08:52:00Z,18.0,6.0,...,5776.527344,254.696030,-47.440784,302.136810,20.866125,134.750717,4.422367,2315.607666,grassland,5118.055664

In [3]:
prey

,class,order,family,genus,species,lat,long,eventDate,day,month,...,bio4,bio5,bio6,bio7,bio8,bio9,dist,dem90_hf,lc_class,ndvi
0,Insecta,Odonata,Libellulidae,Sympetrum,Sympetrum corruptum,37.173971,-121.856329,2020-09-29T08:24:00Z,29.0,9.0,...,4352.049805,289.341888,27.307756,262.034149,89.602631,196.067307,8.935099,352.799927,grassland,6343.969238
1,Malacostraca,Isopoda,Armadillidiidae,Armadillidium,Armadillidium vulgare,37.688580,-122.436608,2021-12-04T14:49:59Z,4.0,12.0,...,2455.836914,217.470047,61.847702,155.622360,107.227386,159.852875,2.005335,112.895271,grassland,4995.110352
2,Insecta,Hymenoptera,Apidae,Bombus,Bombus vosnesenskii,33.774911,-116.679713,2021-06-18T08:52:00Z,18.0,6.0,...,5776.527344,254.696030,-47.440784,302.136810,20.866125,134.750717,4.422367,2315.607666,grassland,5118.055664
3,Insecta,Hymenoptera,Apidae,Apis,Apis mellifera,32.848001,-117.050126,2016-04-17T09:28:00Z,17.0,4.0,...,3539.726807,286.711762,65.920944,220.790817,133.117722,213.238907,4.316342,199.882156,closed_shrubland,3649.374756
4,Insecta,Hemiptera,Lygaeidae,Oncopeltus,Oncopeltus fasciatus,32.739453,-117.133980,2019-04-06T18:44:31Z,6.0,4.0,...,3033.009521,259.712738,81.205818,178.506927,138.277557,205.749908,0.651661,72.789574,urban,3468.256104
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111151,Insecta,Hymenoptera,Formicidae,Pogonomyrmex,Pogonomyrmex californicus,33.660853,-115.721380,1980-04-10T00:00:00Z,10.0,4.0,...,7319.267090,393.674744,34.807846,358.866913,217.827911,227.579758,0.925702,548.778870,barren,1187.127441
111152,Insecta,Hymenoptera,Formicidae,Pogonomyrmex,Pogonomyrmex californicus,35.933333,-116.716667,1998-03-26T00:00:00Z,26.0,3.0,...,8878.634766,442.558167,26.608175,415.950012,141.977646,273.793304,7.429875,-13.553053,grassland,792.632141
111153,Insecta,Hymenoptera,Formicidae,Liometopum,Liometopum occidentale,34.156833,-118.726833,2010-05-21T00:00:00Z,21.0,5.0,...,3962.391846,291.092560,51.291302,239.801269,118.917351,209.822205,2.387915,347.122986,grassland,4219.497559
111154,Insecta,Hymenoptera,Formicidae,Pogonomyrmex,Pogonomyrmex californicus,32.989167,-116.658500,2010-05-25T00:00:00Z,25.0,5.0,...,5537.141602,315.901031,8.395161,307.505859,83.576256,199.928528,6.917791,981.674377,grassland,4865.626465
111155,Insecta,Lepidoptera,Nymphalidae,Vanessa,Vanessa cardui,36.251400,-117.731400,1992-09-02T00:00:00Z,2.0,9.0,...,7069.728027,293.179962,-47.896355,341.076324,20.241280,171.378082,23.553705,1913.307861,grassland,1628.940918

In [6]:
# To see all the column names in the same display we need to set a pandas option. 
# Run the following command and then look at the prey data again:

pd.set_option("display.max_columns", None)
prey

,class,order,family,genus,species,lat,long,eventDate,day,month,year,institutionCode,coordinateUncertaintyInMeters,basisOfRecord,individualCount,datasetKey,ID,bio1,bio10,bio11,bio12,bio13,bio14,bio15,bio16,bio17,bio18,bio19,bio2,bio3,bio4,bio5,bio6,bio7,bio8,bio9,dist,dem90_hf,lc_class,ndvi
0,Insecta,Odonata,Libellulidae,Sympetrum,Sympetrum corruptum,37.173971,-121.856329,2020-09-29T08:24:00Z,29.0,9.0,2020,iNaturalist,684.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,1,141.925064,199.384964,89.602631,727.380493,151.920853,1.809903,89.132339,391.141083,7.979710,13.979711,391.141083,139.787125,53.000000,4352.049805,289.341888,27.307756,262.034149,89.602631,196.067307,8.935099,352.799927,grassland,6343.969238
1,Malacostraca,Isopoda,Armadillidiidae,Armadillidium,Armadillidium vulgare,37.688580,-122.436608,2021-12-04T14:49:59Z,4.0,12.0,2021,iNaturalist,6.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,2,136.366943,165.841537,104.141464,609.651916,126.271736,1.001933,87.368050,318.303192,8.236301,12.390024,318.301269,83.996452,53.266750,2455.836914,217.470047,61.847702,155.622360,107.227386,159.852875,2.005335,112.895271,grassland,4995.110352
2,Insecta,Hymenoptera,Apidae,Bombus,Bombus vosnesenskii,33.774911,-116.679713,2021-06-18T08:52:00Z,18.0,6.0,2021,iNaturalist,31.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,3,82.885788,161.338638,19.747343,724.200195,120.836441,4.910511,70.099121,353.376068,49.060783,77.778824,342.061676,144.624817,47.098640,5776.527344,254.696030,-47.440784,302.136810,20.866125,134.750717,4.422367,2315.607666,grassland,5118.055664
3,Insecta,Hymenoptera,Apidae,Apis,Apis mellifera,32.848001,-117.050126,2016-04-17T09:28:00Z,17.0,4.0,2016,iNaturalist,15.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,4,171.959030,221.238907,130.363754,323.523682,62.686253,1.000000,87.075172,179.273834,4.989321,9.743295,163.154465,118.763413,53.612831,3539.726807,286.711762,65.920944,220.790817,133.117722,213.238907,4.316342,199.882156,closed_shrubland,3649.374756
4,Insecta,Hemiptera,Lygaeidae,Oncopeltus,Oncopeltus fasciatus,32.739453,-117.133980,2019-04-06T18:44:31Z,6.0,4.0,2019,iNaturalist,16.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,5,171.996231,214.353073,136.138779,273.203491,58.141060,1.000000,91.661606,162.390411,4.000000,7.109778,142.560562,91.184349,50.718666,3033.009521,259.712738,81.205818,178.506927,138.277557,205.749908,0.651661,72.789574,urban,3468.256104
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111151,Insecta,Hymenoptera,Formicidae,Pogonomyrmex,Pogonomyrmex californicus,33.660853,-115.721380,1980-04-10T00:00:00Z,10.0,4.0,1980,MCZ,3036.0,PRESERVED_SPECIMEN,1.0,4bfac3ea-8763-4f4b-a71a-76a6f5f243d3,111152,200.539291,297.044373,111.539291,131.447403,21.313471,0.464611,50.358723,45.637127,7.404018,33.626942,44.287857,158.105041,43.560184,7319.267090,393.674744,34.807846,358.866913,217.827911,227.579758,0.925702,548.778870,barren,1187.127441
111152,Insecta,Hymenoptera,Formicidae,Pogonomyrmex,Pogonomyrmex californicus,35.933333,-116.716667,1998-03-26T00:00:00Z,26.0,3.0,1998,MCZ,NaN,PRESERVED_SPECIMEN,2.0,4bfac3ea-8763-4f4b-a71a-76a6f5f243d3,111153,230.166946,344.166931,117.216942,49.012608,8.380343,1.000000,50.700531,21.778294,4.391233,9.430344,19.810688,163.872391,39.000000,8878.634766,442.558167,26.608175,415.950012,141.977646,273.793304,7.429875,-13.553053,grassland,792.632141
111153,Insecta,Hymenoptera,Formicidae,Liometopum,Liometopum occidentale,34.156833,-118.726833,2010-05-21T00:00:00Z,21.0,5.0,2010,MCZ,NaN,PRESERVED_SPECIMEN,40.0,4bfac3ea-8763-4f4b-a71a-76a6f5f243d3,111154,161.271088,216.747421,116.372208,499.779816,106.116470,0.000000,96.797958,289.033630,4.470360,11.920360,279.654663,128.898209,53.252625,3962.391846,291.092560,51.291302,239.801269,118.917351,209.822205,2.387915,347.122986,grassland,4219.497559
111154,Insecta,Hymenoptera,Formicidae,Pogonomyrmex,Pogonomyrmex californicus,32.989167,-116.658500,2010-05-25T00:00:00Z,25.0,5.0,2010,MCZ,NaN,PRESERVED_SPECIMEN,30.0,4bfac3ea-8763-4f4b-a71a-76a6f5f243d3,111155,140.342300,217.269943,76.576256,559.577881,102.406273,3.000000,78.449997,293.045471,25.936378,36.503853,270.567810,154.063629,49.683960,5537.141602,315.901031,8.395161,307.505859,83.576256,199.928528,6.917791,981.674377,grassland,4865.626465
111155,Insecta,Lepidoptera,Nymphalidae,Vanessa,Vanessa cardui,36.251400,-117.731400,1992-09-02T00:00:00Z,2.0,9.0,1992,NTNU-VM,100000.0,PRESERVED_SPECIMEN,1.0,1bec5de3-758c-4ed2-ab13-1597601ad07a,111156,102.202797,197.274719,18.412592,294.105835,48.132629,6.007638,59.663151,133.747376,27.179491,31.660290,133.747376,141.080276,41.000000,7069.728027,293.179962,-47.896355,341.076324,20.241280,171.378082,23.553705,1913.307861,grassland,1628.940918

## pd.DataFrame preliminary exploration
Exploratory methods
- head()
- tail()
- info()
- nunique()
- .shape
- .columns
- .dtypes

## Update column names

Change the column names of `institutionCode` and `datasetKey` to `institution_code` and `dataset_key`, respectively. Make sure you’re actually updating the data frame. 

HINT: look for the documentation on the rename method for pandas.DataFrames.

In [10]:
prey = prey.rename(columns = {'institutionCode' : 'institution_code',
                            'datasetKey' : 'dataset_key' })
prey[['institution_code', 'dataset_key']].head()

  institution_code                           dataset_key
0      iNaturalist  50c9509d-22c7-4a22-a47d-8c48425ef4a7
1      iNaturalist  50c9509d-22c7-4a22-a47d-8c48425ef4a7
2      iNaturalist  50c9509d-22c7-4a22-a47d-8c48425ef4a7
3      iNaturalist  50c9509d-22c7-4a22-a47d-8c48425ef4a7
4      iNaturalist  50c9509d-22c7-4a22-a47d-8c48425ef4a7

## Subsetting

Complete the following subsetting tasks.

- Select only the preserved specimens from prey.
- Select observations between 1992 and 2000.
- Select all rows for columns species and eventDate.
- Select observations that are greater than 37° latitude and less than 39° latitude.

In [53]:
# Select only preserved specimens from prey
prey.columns
prey['basisOfRecord'].unique()
preserved = prey[prey['basisOfRecord'] == "PRESERVED_SPECIMEN"]
preserved.head(2)

,class,order,family,genus,species,lat,long,eventDate,day,month,year,institution_code,coordinateUncertaintyInMeters,basisOfRecord,individualCount,dataset_key,ID,bio1,bio10,bio11,bio12,bio13,bio14,bio15,bio16,bio17,bio18,bio19,bio2,bio3,bio4,bio5,bio6,bio7,bio8,bio9,dist,dem90_hf,lc_class,ndvi
1679,Insecta,Hymenoptera,Apidae,Apis,Apis mellifera,34.340000,-119.410004,2016-11-29T00:00:00Z,29.0,11.0,2016,NaN,NaN,PRESERVED_SPECIMEN,NaN,d8cd16ba-bb74-4420-821e-083f2bac17c2,1680,154.372528,200.300980,114.870407,475.911072,108.406372,0.000000,100.069076,290.060028,2.000000,6.201149,285.269562,129.936645,57.310860,3349.972412,272.703095,47.010059,225.693039,117.870407,194.108063,0.802846,139.021927,grassland,4859.10498
1680,Insecta,Hymenoptera,Xyelidae,Xyela,Xyela concava,38.759998,-119.660004,2016-06-25T00:00:00Z,25.0,6.0,2016,NaN,NaN,PRESERVED_SPECIMEN,NaN,d8cd16ba-bb74-4420-821e-083f2bac17c2,1681,79.070374,170.401947,-1.718157,452.265961,73.694450,12.075387,58.115467,199.897278,44.346771,44.346771,199.846512,160.934799,44.482346,6806.624023,281.522827,-74.999733,356.522553,6.357229,170.401947,NaN,1877.535400,savanna,3379.44165

In [54]:
# Select observations btwn 1992 and 2000
preserved = preserved[preserved['year'].between(1992, 2000)].sort_values('year')

In [55]:
preserved[['species', 'eventDate']]

                           species             eventDate
111155              Vanessa cardui  1992-09-02T00:00:00Z
109629              Apis mellifera  1992-05-11T00:00:00Z
109628          Allograpta obliqua  1992-06-09T00:00:00Z
109622         Bombus vosnesenskii  1992-05-16T00:00:00Z
109618            Ischnura cervula  1992-07-02T00:00:00Z
...                            ...                   ...
48063               Apis mellifera  2000-07-11T00:00:00Z
29807          Sympetrum corruptum  2000-12-29T00:00:00Z
30244               Apis mellifera  2000-09-25T00:00:00Z
5122    Diabrotica undecimpunctata  2000-06-01T00:00:00Z
5374       Polyphylla decemlineata  2000-06-09T00:00:00Z

[801 rows x 2 columns]

In [61]:
preserved[(preserved['lat']> 37) & (preserved['long'] < 39)]

,class,order,family,genus,species,lat,long,eventDate,day,month,year,institution_code,coordinateUncertaintyInMeters,basisOfRecord,individualCount,dataset_key,ID,bio1,bio10,bio11,bio12,bio13,bio14,bio15,bio16,bio17,bio18,bio19,bio2,bio3,bio4,bio5,bio6,bio7,bio8,bio9,dist,dem90_hf,lc_class,ndvi
109629,Insecta,Hymenoptera,Apidae,Apis,Apis mellifera,37.095142,-122.023478,1992-05-11T00:00:00Z,11.0,5.0,1992,UCSC,427.0,PRESERVED_SPECIMEN,NaN,db47a906-257f-40a8-8638-4cb1bf092c2b,109630,137.050003,184.735443,92.505020,845.252380,181.678299,2.000000,90.389961,464.457794,8.993988,14.943988,464.457794,130.659347,56.205513,3642.092529,261.825409,31.499006,230.326401,92.505020,181.383606,3.814049,273.003174,evergreen_needleleaf,8201.350586
43273,Insecta,Hymenoptera,Apidae,Bombus,Bombus vosnesenskii,37.949980,-122.630900,1992-04-11T00:00:00Z,11.0,4.0,1992,USDA-ARS,NaN,PRESERVED_SPECIMEN,NaN,8c04889e-a0ad-4f39-8623-06aa9cf0131d,43274,130.535889,174.348694,89.932411,1054.821533,217.573303,2.000000,88.234993,566.943787,13.000000,19.135572,557.403137,107.106247,53.959980,3357.005371,237.945725,41.745583,196.200134,94.804810,169.909760,4.841482,291.798035,evergreen_broadleaf,7582.831543
43457,Insecta,Hymenoptera,Apidae,Bombus,Bombus vosnesenskii,37.441880,-122.143010,1992-08-10T00:00:00Z,10.0,8.0,1992,USDA-ARS,NaN,PRESERVED_SPECIMEN,NaN,8c04889e-a0ad-4f39-8623-06aa9cf0131d,43458,146.045059,189.536499,97.167130,406.205170,83.578331,1.000000,86.469360,216.049423,5.022072,8.469363,216.049423,112.960800,53.580635,3633.904785,250.469360,41.256332,209.213028,97.167130,187.514420,0.762091,6.156494,urban,4360.342773
43738,Insecta,Hymenoptera,Apidae,Bombus,Bombus vosnesenskii,37.774930,-122.419410,1992-06-12T00:00:00Z,12.0,6.0,1992,USDA-ARS,NaN,PRESERVED_SPECIMEN,NaN,8c04889e-a0ad-4f39-8623-06aa9cf0131d,43739,141.562424,168.908936,109.902733,545.775513,116.360855,1.000000,88.591232,292.997040,7.323142,40.688553,292.997040,78.033356,51.961117,2323.016113,219.255463,70.177017,149.078445,109.902733,161.932327,0.369647,26.539448,urban,1362.293579
43751,Insecta,Hymenoptera,Apidae,Bombus,Bombus vosnesenskii,37.774930,-122.419410,1992-10-17T00:00:00Z,17.0,10.0,1992,USDA-ARS,NaN,PRESERVED_SPECIMEN,NaN,8c04889e-a0ad-4f39-8623-06aa9cf0131d,43752,141.562424,168.908936,109.902733,545.775513,116.360855,1.000000,88.591232,292.997040,7.323142,40.688553,292.997040,78.033356,51.961117,2323.016113,219.255463,70.177017,149.078445,109.902733,161.932327,0.369647,26.539448,urban,1362.293579
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16132,Insecta,Coleoptera,Chrysomelidae,Diabrotica,Diabrotica undecimpunctata,37.909400,-122.686400,1999-04-01T00:00:00Z,NaN,4.0,1999,NHMUK,NaN,PRESERVED_SPECIMEN,1.0,7e380070-f762-11e1-a439-00145eb45e9a,16133,133.506027,170.507111,94.953766,978.265015,204.940735,2.000000,89.592659,531.142944,13.000000,17.637972,522.834228,101.000061,54.831825,2983.158936,229.148438,45.967197,183.181244,99.442551,166.507111,2.064850,61.397858,woody_savanna,5950.313965
42967,Insecta,Hymenoptera,Apidae,Bombus,Bombus vosnesenskii,37.592610,-122.097490,1999-07-11T00:00:00Z,11.0,7.0,1999,USDA-ARS,NaN,PRESERVED_SPECIMEN,NaN,8c04889e-a0ad-4f39-8623-06aa9cf0131d,42968,147.204865,190.983231,99.000000,433.384827,93.621262,1.000000,86.680801,232.427582,6.000000,8.000000,232.427582,104.180557,51.000000,3622.247803,250.125946,46.979164,203.146790,99.000000,187.200897,2.602952,2.756627,NaN,2535.478516
36474,Insecta,Orthoptera,Acrididae,Melanoplus,Melanoplus sanguinipes,37.339386,-121.894956,1999-08-02T00:00:00Z,2.0,8.0,1999,BYU,26452.0,PRESERVED_SPECIMEN,NaN,ae24fb7b-af3c-478c-a1ed-2215a90793cc,36475,153.742569,204.513901,100.210625,396.009491,81.896805,1.000000,86.304230,207.215881,4.000000,9.000000,206.279800,128.274612,52.760620,4114.709473,283.788513,42.549912,241.238617,108.284882,202.063904,0.509858,30.449194,urban,3011.112793
1741,Insecta,Orthoptera,Acrididae,Melanoplus,Melanoplus sanguinipes,37.522500,-118.206944,2000-07-23T00:00:00Z,23.0,7.0,2000,CSU,2000.0,PRESERVED_SPECIMEN,1.0,323b0e80-5e4b-4cc4-936a-d93fc8cae9bc,1742,7.090353,86.143593,-56.522018,499.158325,74.596466,18.393005,44.046761,198.922470,68.051323,81.099709,193.088593,124.665611,43.000000,5818.619629,174.778275,-114.206703,288.984985,-54.073639,57.221279,22.681726,3328.460693,grassland,1301.136597
1746,Insecta,Orthoptera,Acrididae,Melanoplus,Melanoplus sanguinipes,38.696450,-119.998880,2000-09-04T00:00:00Z,4.0,9.0,2000,CSU,2000.0,PRESERVED_SPECIMEN,1.0,323b0e80-5e4b-4cc4-936a-d93fc8cae9bc,1747,35.024010,116.275528,-30.674471,1146.673096,191.761307,15.523396,68.833611,535.531555,64.432434,69.561111,505.288910,128.733948,43.000000,5997.387695,203.454208,-91.975990,295.430206,-19.581268,114.275528,8.972960,2595.387695,savanna,2743.423584